//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppClient.host.gear.cao2246soap {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SOAPServiceSoap", Namespace="http://caonvd.org/")]
    public partial class SOAPService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getAllListOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteSmartPhoneByCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback addSmartPhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateSmartPhoneOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SOAPService() {
            this.Url = global::AppClient.Properties.Settings.Default.AppClient_host_gear_cao2246soap_SOAPService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getAllListCompletedEventHandler getAllListCompleted;
        
        /// <remarks/>
        public event deleteSmartPhoneByCodeCompletedEventHandler deleteSmartPhoneByCodeCompleted;
        
        /// <remarks/>
        public event searchByNameCompletedEventHandler searchByNameCompleted;
        
        /// <remarks/>
        public event addSmartPhoneCompletedEventHandler addSmartPhoneCompleted;
        
        /// <remarks/>
        public event updateSmartPhoneCompletedEventHandler updateSmartPhoneCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://caonvd.org/getAllList", RequestNamespace="http://caonvd.org/", ResponseNamespace="http://caonvd.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Smartphone[] getAllList() {
            object[] results = this.Invoke("getAllList", new object[0]);
            return ((Smartphone[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllListAsync() {
            this.getAllListAsync(null);
        }
        
        /// <remarks/>
        public void getAllListAsync(object userState) {
            if ((this.getAllListOperationCompleted == null)) {
                this.getAllListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllListOperationCompleted);
            }
            this.InvokeAsync("getAllList", new object[0], this.getAllListOperationCompleted, userState);
        }
        
        private void OngetAllListOperationCompleted(object arg) {
            if ((this.getAllListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllListCompleted(this, new getAllListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://caonvd.org/deleteSmartPhoneByCode", RequestNamespace="http://caonvd.org/", ResponseNamespace="http://caonvd.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool deleteSmartPhoneByCode(int code) {
            object[] results = this.Invoke("deleteSmartPhoneByCode", new object[] {
                        code});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteSmartPhoneByCodeAsync(int code) {
            this.deleteSmartPhoneByCodeAsync(code, null);
        }
        
        /// <remarks/>
        public void deleteSmartPhoneByCodeAsync(int code, object userState) {
            if ((this.deleteSmartPhoneByCodeOperationCompleted == null)) {
                this.deleteSmartPhoneByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteSmartPhoneByCodeOperationCompleted);
            }
            this.InvokeAsync("deleteSmartPhoneByCode", new object[] {
                        code}, this.deleteSmartPhoneByCodeOperationCompleted, userState);
        }
        
        private void OndeleteSmartPhoneByCodeOperationCompleted(object arg) {
            if ((this.deleteSmartPhoneByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteSmartPhoneByCodeCompleted(this, new deleteSmartPhoneByCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://caonvd.org/searchByName", RequestNamespace="http://caonvd.org/", ResponseNamespace="http://caonvd.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Smartphone[] searchByName(string keyword) {
            object[] results = this.Invoke("searchByName", new object[] {
                        keyword});
            return ((Smartphone[])(results[0]));
        }
        
        /// <remarks/>
        public void searchByNameAsync(string keyword) {
            this.searchByNameAsync(keyword, null);
        }
        
        /// <remarks/>
        public void searchByNameAsync(string keyword, object userState) {
            if ((this.searchByNameOperationCompleted == null)) {
                this.searchByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchByNameOperationCompleted);
            }
            this.InvokeAsync("searchByName", new object[] {
                        keyword}, this.searchByNameOperationCompleted, userState);
        }
        
        private void OnsearchByNameOperationCompleted(object arg) {
            if ((this.searchByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchByNameCompleted(this, new searchByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://caonvd.org/addSmartPhone", RequestNamespace="http://caonvd.org/", ResponseNamespace="http://caonvd.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addSmartPhone(Smartphone smartPhone) {
            object[] results = this.Invoke("addSmartPhone", new object[] {
                        smartPhone});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addSmartPhoneAsync(Smartphone smartPhone) {
            this.addSmartPhoneAsync(smartPhone, null);
        }
        
        /// <remarks/>
        public void addSmartPhoneAsync(Smartphone smartPhone, object userState) {
            if ((this.addSmartPhoneOperationCompleted == null)) {
                this.addSmartPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddSmartPhoneOperationCompleted);
            }
            this.InvokeAsync("addSmartPhone", new object[] {
                        smartPhone}, this.addSmartPhoneOperationCompleted, userState);
        }
        
        private void OnaddSmartPhoneOperationCompleted(object arg) {
            if ((this.addSmartPhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addSmartPhoneCompleted(this, new addSmartPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://caonvd.org/updateSmartPhone", RequestNamespace="http://caonvd.org/", ResponseNamespace="http://caonvd.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateSmartPhone(Smartphone smartPhone) {
            object[] results = this.Invoke("updateSmartPhone", new object[] {
                        smartPhone});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateSmartPhoneAsync(Smartphone smartPhone) {
            this.updateSmartPhoneAsync(smartPhone, null);
        }
        
        /// <remarks/>
        public void updateSmartPhoneAsync(Smartphone smartPhone, object userState) {
            if ((this.updateSmartPhoneOperationCompleted == null)) {
                this.updateSmartPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateSmartPhoneOperationCompleted);
            }
            this.InvokeAsync("updateSmartPhone", new object[] {
                        smartPhone}, this.updateSmartPhoneOperationCompleted, userState);
        }
        
        private void OnupdateSmartPhoneOperationCompleted(object arg) {
            if ((this.updateSmartPhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateSmartPhoneCompleted(this, new updateSmartPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://caonvd.org/")]
    public partial class Smartphone {
        
        private int codeField;
        
        private string nameField;
        
        private System.Nullable<int> priceField;
        
        private string brandField;
        
        private string colorField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getAllListCompletedEventHandler(object sender, getAllListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Smartphone[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Smartphone[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void deleteSmartPhoneByCodeCompletedEventHandler(object sender, deleteSmartPhoneByCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteSmartPhoneByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteSmartPhoneByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void searchByNameCompletedEventHandler(object sender, searchByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Smartphone[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Smartphone[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void addSmartPhoneCompletedEventHandler(object sender, addSmartPhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addSmartPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addSmartPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void updateSmartPhoneCompletedEventHandler(object sender, updateSmartPhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateSmartPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateSmartPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591